config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get "tasks", to: "tasks#index"
get "tasks/new", to: "tasks#new", as: :new
post "tasks", to: "tasks#create"
get "tasks/:id", to: "tasks#show", as: :task
get "tasks/:id/edit", to: "tasks#edit", as: :edit
patch "tasks/:id", to: "tasks#update"
delete "tasks/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

   def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)

    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a Task</h1>
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= check_box_tag :completed, "1", task.completed, disabled: true %><%= link_to task.title, task_path(task) %> - <%= link_to "remove", destroy_path(destroy) %></li>
  <% end %>
</ul>
<div><%= link_to "Add a new task", new_path %></div>

app/views/tasks/new.html.erb
<h1>Add a Task</h1>
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>
<div class = container>
<p><%= @task.details%></p>
</div>
<p><%= @task.completed%></p>
<hr>
<div>
<%= link_to "Back to List", tasks_path %>
</div>
<div>
<%= link_to "Edit this task", edit_path %>
</div>